server:
  port: 8080
  error:
    include-message: never
    include-stacktrace: never

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%X{correlationId:-}] %logger{36} : %msg%n"

spring:
  application:
    name: transfer-service
  r2dbc:
    url: r2dbc:postgresql://postgres:5432/transfers
    username: transfers
    password: transfers
  flyway:
    url: jdbc:postgresql://postgres:5432/transfers
    user: transfers
    password: transfers

acme:
  accounts-url: http://mock-bank:9090
  fx-url: http://mock-bank:9090
  fraud-url: http://mock-bank:9090
  core-url: http://mock-bank:9090
  core-read-timeout-ms: 2000
  fraud-threshold:
    idr: 75000000.00
    usd: 5000.00
    sgd: 6500.00
